"""Analytics domain models.

Data model overview
-------------------
* ``videos``            — dimension table describing each piece of content.
* ``impression_events`` — top of the funnel: a video surfaced to a viewer.
* ``view_events``       — a viewer actually started watching; carries watch
                          time, engagement flags, geo and device dimensions.

The two event tables are append-only "fact" tables. All dashboard queries are
aggregations over these tables sliced by time / video / dimension, which is why
the indexing strategy below matters (see README for the full rationale).
"""

import enum
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class DeviceType(enum.StrEnum):
    mobile = "mobile"
    desktop = "desktop"
    tablet = "tablet"
    tv = "tv"


class Video(Base):
    __tablename__ = "videos"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    category: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    duration_seconds: Mapped[int] = mapped_column(Integer, nullable=False)
    published_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    thumbnail_url: Mapped[str | None] = mapped_column(String(512))

    views: Mapped[list["ViewEvent"]] = relationship(back_populates="video")


class ImpressionEvent(Base):
    """A video was shown to a viewer (top of the engagement funnel)."""

    __tablename__ = "impression_events"

    id: Mapped[int] = mapped_column(primary_key=True)
    video_id: Mapped[int] = mapped_column(
        ForeignKey("videos.id", ondelete="CASCADE"), nullable=False
    )
    event_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    country_code: Mapped[str] = mapped_column(String(2), nullable=False)
    device_type: Mapped[str] = mapped_column(String(16), nullable=False)

    __table_args__ = (
        # Covers time-range scans and per-video time-range scans (the two most
        # common access patterns) with a single composite b-tree index.
        Index("ix_impressions_video_time", "video_id", "event_time"),
        Index("ix_impressions_time", "event_time"),
    )


class ViewEvent(Base):
    """A viewer started watching a video. Carries all engagement measures."""

    __tablename__ = "view_events"

    id: Mapped[int] = mapped_column(primary_key=True)
    video_id: Mapped[int] = mapped_column(
        ForeignKey("videos.id", ondelete="CASCADE"), nullable=False
    )
    # A pseudonymous viewer identifier used to count unique viewers. Not a
    # real person — generated by the seed script.
    viewer_id: Mapped[str] = mapped_column(String(36), nullable=False)
    event_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    country_code: Mapped[str] = mapped_column(String(2), nullable=False)
    device_type: Mapped[str] = mapped_column(String(16), nullable=False)

    watch_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    # Highest quartile of the video the viewer reached (0..4 -> 0/25/50/75/100%).
    quartile_reached: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    liked: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    commented: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    shared: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    video: Mapped["Video"] = relationship(back_populates="views")

    __table_args__ = (
        CheckConstraint("quartile_reached BETWEEN 0 AND 4", name="ck_quartile_range"),
        # Primary access pattern: filter by date range (all dashboards do this).
        Index("ix_views_time", "event_time"),
        # Per-video date-range queries + "top videos in period" aggregation.
        Index("ix_views_video_time", "video_id", "event_time"),
        # Geographic aggregation sliced by time.
        Index("ix_views_country_time", "country_code", "event_time"),
        # Device aggregation sliced by time.
        Index("ix_views_device_time", "device_type", "event_time"),
    )
